# general
gpu_id: 3
use_gpu: True
seed: 42
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False
loss_type: CE
neg_sampling: ~
train_batch_size: 256
eval_batch_size : 256
# model (SimDiff)
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_act: gelu
initializer_range: 0.02
layer_norm_eps: 1e-12
attn_dropout_prob: 0.2
hidden_dropout_prob: 0.2
mask_strategy: sample
mask_ratio: 0.2
encoder_loss_weight: 1
contrastive_loss_weight: 0.4
generate_loss_weight: 0.4
n_embedding: 30
n_sampling: 5
generate_method: ~

# dataset
load_col:
    inter: [user_id, item_id, rating, timestamp]
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp

# Filtering
rm_dup_inter: "first"
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

group_size: 25